---
- name: Installing application server SW NGINX
  yum: name=nginx state=present

- name: Copy virtual config file to nginx conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=644
  notify:
  - enable-docroot&nginx-changes
  
- name: get the cpu count & assigned to nginx worker_processes
  shell: grep processor /proc/cpuinfo | wc -l
  register: worker_processes_out

- name: set fact of worker_processes
  set_fact:
   worker_processes: "{{ worker_processes_out.stdout }}"

- name: get the core limit & assigned to nginx worker_connections
  shell: ulimit -n
  register: worker_connections_out

- name: set fact of worker_connections
  set_fact:
   worker_connections: "{{ worker_connections_out.stdout }}"

- name: Set Nginx worker_processes
  lineinfile: 
    path: /etc/nginx/nginx.conf
    regexp: '^worker_processes'
    line: 'worker_processes {{ worker_processes }};'
    state: present
  notify: enable-docroot&nginx-changes

- name: Set Nginx worker_connections
  lineinfile: 
    path: /etc/nginx/nginx.conf
    regexp: '^events'
    line: 'events { worker_connections {{ worker_connections }};}'
    state: present
  notify: enable-docroot&nginx-changes 

- name: Copy virtual config file to nginx conf
  template: src=celerone.conf dest=/etc/nginx/conf.d/celerone.conf owner=root group=root mode=644
  notify:
  - enable-docroot&nginx-changes

- name: Creates docroot directory
  file: path=/var/www state=directory 

- name: "Application Document root"
  template: src=local.html dest=/var/www/local.html owner=root group=root mode=777
  notify:
  - enable-docroot&nginx-changes

- name: Ensure NGINX is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes