---
- name: "Installing Balancer Software HAProxy"
  yum: name=haproxy state=present

- name: "Configure Haproxy"
  template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=644
  notify:
  - enable-proxyip-changes

- name: "Start HAProxy"
  service: name=haproxy state=running

