-name: "Installing Balancer Software HAProxy"
 yum: name=haproxy state=present

#-name: "Configure Haproxy"
# template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg

-name: "Start HAProxy"
 service: name=haproxy state=running

