---
- name: enable-proxyip&haproxy-changes
  service: name=haproxy state=restarted
  
- name: restart_haproxy
  service: name=haproxy state=restarted

- name: reload_haproxy
  service: name=haproxy state=reloaded